//Barra buscadora
let suggestions = [
    "Nike",
    "Adidas",
    "Zapatillas Nike",
    "Zapatillas Adidas",
    "Pelotas de Futbol",
    "Pelotas de Basquet",
    "Pelotas de Volley",
    "Pelotas de Tenis",
    "Pelotas de Ping Pong",
    "Camisetas de Futbol",
    "Camisetas de Argentina",
    "Camisetas de Boca",
    "Camisetas de River",
    "Camisetas de San Lorenzo",
    "Camisetas de Racing",
    "Camisetas de Huracan",
    "Camisetas de Barcelona",
    "Camisetas de Paris Saint Germain",
    "Camisetas de Atletico Madrid",
    "Camisetas de Real Madrid",
];